# SEC EDGAR Income Statement Extractor

This notebook downloads and parses income statements from SEC filings (10-K/10-Q) using edgartools.

## Features
- Handles both annual (10-K) and quarterly (10-Q) filings
- Extracts comprehensive income statement line items
- Works for any fiscal year or quarter
- Proper SEC identity setup to avoid 403 blocks

## 1. Setup and Imports

In [85]:
import os
from pathlib import Path
from datetime import datetime
from dotenv import load_dotenv
import pandas as pd
from edgar import Company, set_identity
from typing import Optional, Literal

# Load environment variables
load_dotenv()

# Set SEC identity to avoid 403 blocks
sec_identity = os.getenv("SEC_ID")
if not sec_identity:
    raise ValueError("SEC_ID not found in .env file")

set_identity(sec_identity)
print(f"✓ SEC identity set: {sec_identity}")

2026-01-29 05:40:41,910 - INFO - Identity of the Edgar REST client set to [pedroemail@duck.com]

✓ SEC identity set: pedroemail@duck.com

## 2. Define Income Statement Line Item Mapping

Map common XBRL tags to standardized income statement line items.

In [86]:
# XBRL concept mapping for income statement line items
INCOME_STATEMENT_MAPPING = {
    # Revenue Section
    "Revenue": [
        "Revenues",
        "RevenueFromContractWithCustomerExcludingAssessedTax",
        "RevenueFromContractWithCustomerIncludingAssessedTax",
        "SalesRevenueNet",
        "SalesRevenueGoodsNet",
        "SalesRevenueServicesNet",
    ],
    "Cost of Revenue": [
        "CostOfRevenue",
        "CostOfGoodsAndServicesSold",
        "CostOfGoodsSold",
        "CostOfServices",
    ],
    "Gross Profit": [
        "GrossProfit",
    ],
    
    # Operating Expenses
    "Research & Development": [
        "ResearchAndDevelopmentExpense",
        "ResearchAndDevelopmentExpenseExcludingAcquiredInProcessCost",
    ],
    "Selling, General & Administrative": [
        "SellingGeneralAndAdministrativeExpense",
        "SellingAndMarketingExpense",
        "GeneralAndAdministrativeExpense",
    ],
    "Depreciation & Amortization": [
        "DepreciationDepletionAndAmortization",
        "DepreciationAndAmortization",
        "Depreciation",
        "AmortizationOfIntangibleAssets",
    ],
    "Other Operating Expenses": [
        "OtherOperatingIncomeExpenseNet",
        "OtherCostAndExpenseOperating",
    ],
    "Operating Income": [
        "OperatingIncomeLoss",
        "IncomeLossFromContinuingOperationsBeforeIncomeTaxesMinorityInterestAndIncomeLossFromEquityMethodInvestments",
    ],
    
    # Non-Operating Items
    "Interest Income": [
        "InterestIncomeOther",
        "InvestmentIncomeInterest",
        "InterestAndDividendIncomeOperating",
    ],
    "Interest Expense": [
        "InterestExpense",
        "InterestExpenseDebt",
    ],
    "Other Income/Expense": [
        "OtherNonoperatingIncomeExpense",
        "NonoperatingIncomeExpense",
        "OtherIncome",
    ],
    "Gains/Losses on Investments": [
        "GainLossOnInvestments",
        "GainLossOnSaleOfInvestments",
        "MarketableSecuritiesGainLoss",
    ],
    "Pretax Income": [
        "IncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest",
        "IncomeLossFromContinuingOperationsBeforeIncomeTaxesMinorityInterestAndIncomeLossFromEquityMethodInvestments",
    ],
    
    # Taxes & Net Income
    "Income Tax Expense": [
        "IncomeTaxExpenseBenefit",
        "IncomeTaxesPaid",
    ],
    "Net Income from Continuing Operations": [
        "IncomeLossFromContinuingOperations",
        "IncomeLossFromContinuingOperationsIncludingPortionAttributableToNoncontrollingInterest",
    ],
    "Discontinued Operations": [
        "IncomeLossFromDiscontinuedOperationsNetOfTax",
        "DiscontinuedOperationIncomeLossFromDiscontinuedOperationDuringPhaseOutPeriodNetOfTax",
    ],
    "Net Income": [
        "NetIncomeLoss",
        "ProfitLoss",
        "NetIncomeLossAvailableToCommonStockholdersBasic",
    ],
    "Net Income Attributable to Noncontrolling Interests": [
        "NetIncomeLossAttributableToNoncontrollingInterest",
        "MinorityInterestNetOfTax",
    ],
    "Net Income Attributable to Common Shareholders": [
        "NetIncomeLossAvailableToCommonStockholdersBasic",
        "NetIncomeLossAvailableToCommonStockholdersDiluted",
    ],
    
    # Per Share Data
    "Basic EPS": [
        "EarningsPerShareBasic",
    ],
    "Diluted EPS": [
        "EarningsPerShareDiluted",
    ],
    "Basic Weighted Average Shares Outstanding": [
        "WeightedAverageNumberOfSharesOutstandingBasic",
        "WeightedAverageNumberOfShareOutstandingBasicAndDiluted",
    ],
    "Diluted Weighted Average Shares Outstanding": [
        "WeightedAverageNumberOfDilutedSharesOutstanding",
    ],
}

print(f"✓ Defined {len(INCOME_STATEMENT_MAPPING)} income statement line items")

✓ Defined 23 income statement line items

## 3. Function to Get Filing

In [108]:
def parse_date(date_str):
    """Parse a date string to datetime object."""
    if isinstance(date_str, str):
        try:
            return pd.to_datetime(date_str)
        except Exception:
            return None
    return date_str

def get_filing(
    ticker: str,
    filing_type: Literal["10-K", "10-Q"],
    year: Optional[int] = None,
    quarter: Optional[int] = None
):
    """
    Retrieve a specific SEC filing for a company.
    
    Args:
        ticker: Company ticker symbol
        filing_type: Either "10-K" (annual) or "10-Q" (quarterly)
        year: Fiscal year (if None, gets the most recent)
        quarter: Fiscal quarter (1-4, only for 10-Q)
        
    Returns:
        Filing object from edgartools
        
    Raises:
        ValueError: If parameters are invalid
        FileNotFoundError: If filing is not found
    """
    if filing_type == "10-Q" and quarter is not None:
        if not 1 <= quarter <= 4:
            raise ValueError("Quarter must be between 1 and 4")
    
    # Get company
    company = Company(ticker)
    print(f"✓ Retrieved company: {company.name} ({ticker})")
    
    # Get filings of the specified type
    filings = company.get_filings(form=filing_type)
    
    if filings.empty:
        raise FileNotFoundError(f"No {filing_type} filings found for {ticker}")
    
    # Filter by year if specified
    if year is not None:
        filings_filtered = []
        
        for f in filings:
            # Parse dates
            filing_date = parse_date(f.filing_date) if hasattr(f, 'filing_date') else None
            period_date = parse_date(f.period_of_report) if hasattr(f, 'period_of_report') else None
            
            # Check if either date matches the year
            filing_year_match = filing_date and filing_date.year == year
            period_year_match = period_date and period_date.year == year
            
            if filing_year_match or period_year_match:
                # Store the parsed dates for later use
                f._parsed_filing_date = filing_date
                f._parsed_period_date = period_date
                filings_filtered.append(f)
        
        if not filings_filtered:
            raise FileNotFoundError(f"No {filing_type} filings found for {ticker} in year {year}")
        
        # For 10-Q, further filter by quarter if specified
        if filing_type == "10-Q" and quarter is not None:
            quarter_filtered = []
            
            for f in filings_filtered:
                period_date = f._parsed_period_date
                if period_date:
                    # Calculate quarter from month (Q1: Jan-Mar, Q2: Apr-Jun, Q3: Jul-Sep, Q4: Oct-Dec)
                    file_quarter = ((period_date.month - 1) // 3) + 1
                    if file_quarter == quarter:
                        quarter_filtered.append(f)
            
            if not quarter_filtered:
                raise FileNotFoundError(
                    f"No {filing_type} filings found for {ticker} in Q{quarter} {year}"
                )
            
            filings_filtered = quarter_filtered
        
        filing = filings_filtered[0]
    else:
        # Get the most recent filing
        filing = filings[0]
    
    filing_date = filing.filing_date if hasattr(filing, 'filing_date') else 'Unknown'
    period = filing.period_of_report if hasattr(filing, 'period_of_report') else 'Unknown'
    
    print(f"✓ Retrieved {filing_type} filing")
    print(f"  Filing Date: {filing_date}")
    print(f"  Period of Report: {period}")
    
    return filing

# Test the function with a well-known company
test_filing = get_filing("AAPL", "10-K", year=2023)
print(f"\n✓ Test successful")

2026-01-29 06:14:50,619 - INFO - No cache policy for data.sec.gov:///submissions/CIK0000320193.json, not retrieving from cache
2026-01-29 06:14:50,620 - INFO - Making HTTP Request <Request('GET', 'https://data.sec.gov/submissions/CIK0000320193.json')>
2026-01-29 06:14:50,833 - INFO - HTTP Request: GET https://data.sec.gov/submissions/CIK0000320193.json "HTTP/1.1 200 OK"
2026-01-29 06:14:50,858 - INFO - No cache policy for data.sec.gov:///submissions/CIK0000320193-submissions-001.json, not retrieving from cache
2026-01-29 06:14:50,858 - INFO - Making HTTP Request <Request('GET', 'https://data.sec.gov/submissions/CIK0000320193-submissions-001.json')>
2026-01-29 06:14:50,960 - INFO - HTTP Request: GET https://data.sec.gov/submissions/CIK0000320193-submissions-001.json "HTTP/1.1 200 OK"
2026-01-29 06:14:50,971 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:14:50,972 - INFO - /Archives/edgar/data/320193/000032019325000079/0000320193-25-000079.txt matched /Archives/edgar/data, using value True
2026-01-29 06:14:50,973 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000032019325000079-0000320193-25-000079.txt
2026-01-29 06:14:50,990 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000032019325000079/0000320193-25-000079.txt "HTTP/1.1 200 OK"
2026-01-29 06:14:51,058 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}

✓ Retrieved company: Apple Inc. (AAPL)

2026-01-29 06:14:51,059 - INFO - /Archives/edgar/data/320193/000032019324000123/0000320193-24-000123.txt matched /Archives/edgar/data, using value True
2026-01-29 06:14:51,061 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000032019324000123-0000320193-24-000123.txt
2026-01-29 06:14:51,077 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000032019324000123/0000320193-24-000123.txt "HTTP/1.1 200 OK"
2026-01-29 06:14:51,131 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:14:51,132 - INFO - /Archives/edgar/data/320193/000032019323000106/0000320193-23-000106.txt matched /Archives/edgar/data, using value True
2026-01-29 06:14:51,134 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000032019323000106-0000320193-23-000106.txt
2026-01-29 06:14:51,164 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000032019323000106/0000320193-23-000106.txt "HTTP/1.1 200 OK"
2026-01-29 06:14:51,231 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:14:51,232 - INFO - /Archives/edgar/data/320193/000032019322000108/0000320193-22-000108.txt matched /Archives/edgar/data, using value True
2026-01-29 06:14:51,234 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000032019322000108-0000320193-22-000108.txt
2026-01-29 06:14:51,263 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000032019322000108/0000320193-22-000108.txt "HTTP/1.1 200 OK"
2026-01-29 06:14:51,330 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:14:51,331 - INFO - /Archives/edgar/data/320193/000032019321000105/0000320193-21-000105.txt matched /Archives/edgar/data, using value True
2026-01-29 06:14:51,344 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000032019321000105-0000320193-21-000105.txt
2026-01-29 06:14:51,372 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000032019321000105/0000320193-21-000105.txt "HTTP/1.1 200 OK"
2026-01-29 06:14:51,447 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:14:51,448 - INFO - /Archives/edgar/data/320193/000032019320000096/0000320193-20-000096.txt matched /Archives/edgar/data, using value True
2026-01-29 06:14:51,450 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000032019320000096-0000320193-20-000096.txt
2026-01-29 06:14:51,480 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000032019320000096/0000320193-20-000096.txt "HTTP/1.1 200 OK"
2026-01-29 06:14:51,613 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:14:51,613 - INFO - /Archives/edgar/data/320193/000032019319000119/0000320193-19-000119.txt matched /Archives/edgar/data, using value True
2026-01-29 06:14:51,615 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000032019319000119-0000320193-19-000119.txt
2026-01-29 06:14:51,636 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000032019319000119/0000320193-19-000119.txt "HTTP/1.1 200 OK"
2026-01-29 06:14:51,733 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:14:51,733 - INFO - /Archives/edgar/data/320193/000032019318000145/0000320193-18-000145.txt matched /Archives/edgar/data, using value True
2026-01-29 06:14:51,736 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000032019318000145-0000320193-18-000145.txt
2026-01-29 06:14:51,750 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000032019318000145/0000320193-18-000145.txt "HTTP/1.1 200 OK"
2026-01-29 06:14:51,810 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:14:51,812 - INFO - /Archives/edgar/data/320193/000032019317000070/0000320193-17-000070.txt matched /Archives/edgar/data, using value True
2026-01-29 06:14:51,821 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000032019317000070-0000320193-17-000070.txt
2026-01-29 06:14:51,867 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000032019317000070/0000320193-17-000070.txt "HTTP/1.1 200 OK"
2026-01-29 06:14:51,920 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:14:51,922 - INFO - /Archives/edgar/data/320193/000162828016020309/0001628280-16-020309.txt matched /Archives/edgar/data, using value True
2026-01-29 06:14:51,928 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000162828016020309-0001628280-16-020309.txt
2026-01-29 06:14:51,954 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000162828016020309/0001628280-16-020309.txt "HTTP/1.1 200 OK"
2026-01-29 06:14:52,017 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:14:52,017 - INFO - /Archives/edgar/data/320193/000119312515356351/0001193125-15-356351.txt matched /Archives/edgar/data, using value True
2026-01-29 06:14:52,019 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000119312515356351-0001193125-15-356351.txt
2026-01-29 06:14:52,044 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000119312515356351/0001193125-15-356351.txt "HTTP/1.1 200 OK"
2026-01-29 06:14:52,117 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:14:52,117 - INFO - /Archives/edgar/data/320193/000119312514383437/0001193125-14-383437.txt matched /Archives/edgar/data, using value True
2026-01-29 06:14:52,119 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000119312514383437-0001193125-14-383437.txt
2026-01-29 06:14:52,151 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000119312514383437/0001193125-14-383437.txt "HTTP/1.1 200 OK"
2026-01-29 06:14:52,237 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:14:52,237 - INFO - /Archives/edgar/data/320193/000119312513416534/0001193125-13-416534.txt matched /Archives/edgar/data, using value True
2026-01-29 06:14:52,239 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000119312513416534-0001193125-13-416534.txt
2026-01-29 06:14:52,255 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000119312513416534/0001193125-13-416534.txt "HTTP/1.1 200 OK"
2026-01-29 06:14:52,342 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:14:52,343 - INFO - /Archives/edgar/data/320193/000119312512444068/0001193125-12-444068.txt matched /Archives/edgar/data, using value True
2026-01-29 06:14:52,345 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000119312512444068-0001193125-12-444068.txt
2026-01-29 06:14:52,360 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000119312512444068/0001193125-12-444068.txt "HTTP/1.1 200 OK"
2026-01-29 06:14:52,444 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:14:52,444 - INFO - /Archives/edgar/data/320193/000119312511282113/0001193125-11-282113.txt matched /Archives/edgar/data, using value True
2026-01-29 06:14:52,446 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000119312511282113-0001193125-11-282113.txt
2026-01-29 06:14:52,462 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000119312511282113/0001193125-11-282113.txt "HTTP/1.1 200 OK"
2026-01-29 06:14:52,545 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:14:52,546 - INFO - /Archives/edgar/data/320193/000119312510238044/0001193125-10-238044.txt matched /Archives/edgar/data, using value True
2026-01-29 06:14:52,548 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000119312510238044-0001193125-10-238044.txt
2026-01-29 06:14:52,579 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000119312510238044/0001193125-10-238044.txt "HTTP/1.1 200 OK"
2026-01-29 06:14:52,758 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:14:52,759 - INFO - /Archives/edgar/data/320193/000119312510012091/0001193125-10-012091.txt matched /Archives/edgar/data, using value True
2026-01-29 06:14:52,761 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000119312510012091-0001193125-10-012091.txt
2026-01-29 06:14:52,767 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000119312510012091/0001193125-10-012091.txt "HTTP/1.1 200 OK"
2026-01-29 06:14:52,821 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:14:52,822 - INFO - /Archives/edgar/data/320193/000119312509214859/0001193125-09-214859.txt matched /Archives/edgar/data, using value True
2026-01-29 06:14:52,824 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000119312509214859-0001193125-09-214859.txt
2026-01-29 06:14:52,830 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000119312509214859/0001193125-09-214859.txt "HTTP/1.1 200 OK"
2026-01-29 06:14:52,855 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:14:52,856 - INFO - /Archives/edgar/data/320193/000119312508224958/0001193125-08-224958.txt matched /Archives/edgar/data, using value True
2026-01-29 06:14:52,857 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000119312508224958-0001193125-08-224958.txt
2026-01-29 06:14:52,861 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000119312508224958/0001193125-08-224958.txt "HTTP/1.1 200 OK"
2026-01-29 06:14:52,870 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:14:52,872 - INFO - /Archives/edgar/data/320193/000104746907009340/0001047469-07-009340.txt matched /Archives/edgar/data, using value True
2026-01-29 06:14:52,873 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000104746907009340-0001047469-07-009340.txt
2026-01-29 06:14:52,880 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000104746907009340/0001047469-07-009340.txt "HTTP/1.1 200 OK"
2026-01-29 06:14:52,911 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:14:52,914 - INFO - /Archives/edgar/data/320193/000110465906084288/0001104659-06-084288.txt matched /Archives/edgar/data, using value True
2026-01-29 06:14:52,915 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000110465906084288-0001104659-06-084288.txt
2026-01-29 06:14:52,923 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000110465906084288/0001104659-06-084288.txt "HTTP/1.1 200 OK"
2026-01-29 06:14:52,947 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:14:52,947 - INFO - /Archives/edgar/data/320193/000110465905058421/0001104659-05-058421.txt matched /Archives/edgar/data, using value True
2026-01-29 06:14:52,948 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000110465905058421-0001104659-05-058421.txt
2026-01-29 06:14:52,953 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000110465905058421/0001104659-05-058421.txt "HTTP/1.1 200 OK"
2026-01-29 06:14:52,972 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:14:52,973 - INFO - /Archives/edgar/data/320193/000104746904035975/0001047469-04-035975.txt matched /Archives/edgar/data, using value True
2026-01-29 06:14:52,974 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000104746904035975-0001047469-04-035975.txt
2026-01-29 06:14:52,977 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000104746904035975/0001047469-04-035975.txt "HTTP/1.1 200 OK"
2026-01-29 06:14:52,998 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:14:52,999 - INFO - /Archives/edgar/data/320193/000104746903041604/0001047469-03-041604.txt matched /Archives/edgar/data, using value True
2026-01-29 06:14:52,999 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000104746903041604-0001047469-03-041604.txt
2026-01-29 06:14:53,004 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000104746903041604/0001047469-03-041604.txt "HTTP/1.1 200 OK"
2026-01-29 06:14:53,019 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:14:53,019 - INFO - /Archives/edgar/data/320193/000104746902007674/0001047469-02-007674.txt matched /Archives/edgar/data, using value True
2026-01-29 06:14:53,021 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000104746902007674-0001047469-02-007674.txt
2026-01-29 06:14:53,039 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000104746902007674/0001047469-02-007674.txt "HTTP/1.1 200 OK"
2026-01-29 06:14:53,047 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:14:53,047 - INFO - /Archives/edgar/data/320193/000091205700053623/0000912057-00-053623.txt matched /Archives/edgar/data, using value True
2026-01-29 06:14:53,048 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000091205700053623-0000912057-00-053623.txt
2026-01-29 06:14:53,050 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000091205700053623/0000912057-00-053623.txt "HTTP/1.1 200 OK"
2026-01-29 06:14:53,054 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:14:53,055 - INFO - /Archives/edgar/data/320193/000091205799010244/0000912057-99-010244.txt matched /Archives/edgar/data, using value True
2026-01-29 06:14:53,056 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000091205799010244-0000912057-99-010244.txt
2026-01-29 06:14:53,058 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000091205799010244/0000912057-99-010244.txt "HTTP/1.1 200 OK"
2026-01-29 06:14:53,065 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:14:53,065 - INFO - /Archives/edgar/data/320193/000104746998001822/0001047469-98-001822.txt matched /Archives/edgar/data, using value True
2026-01-29 06:14:53,067 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000104746998001822-0001047469-98-001822.txt
2026-01-29 06:14:53,068 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000104746998001822/0001047469-98-001822.txt "HTTP/1.1 200 OK"
2026-01-29 06:14:53,071 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:14:53,072 - INFO - /Archives/edgar/data/320193/000104746997006960/0001047469-97-006960.txt matched /Archives/edgar/data, using value True
2026-01-29 06:14:53,073 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000104746997006960-0001047469-97-006960.txt

✓ Retrieved 10-K filing
  Filing Date: 2023-11-03
  Period of Report: 2023-09-30

✓ Test successful

## 4. Extract Income Statement Data

In [109]:
def get_fact_value(xbrl, concept_name: str, end_date: str, prefer_shortest: bool = True):
    """
    Get a specific fact value from XBRL, preferring the shortest duration for the given end date.
    
    Args:
        xbrl: XBRL object
        concept_name: The XBRL concept to search for  
        end_date: The end date in YYYY-MM-DD format
        prefer_shortest: If True, prefer the shortest duration period
        
    Returns:
        The value, or None if not found
    """
    try:
        # Query facts for the concept
        facts = xbrl.facts.query().by_concept(concept_name).to_dataframe()
        
        if facts.empty:
            return None
        
        # Filter by end date
        date_filtered = facts[facts['end'] == end_date] if 'end' in facts.columns else facts
        
        if date_filtered.empty:
            return None
        
        # Filter out dimensional breakdowns (segments, product lines, etc.)
        # We only want consolidated totals
        if 'dimensions' in date_filtered.columns:
            # Prefer facts with no dimensions (consolidated totals)
            no_dimensions = date_filtered[date_filtered['dimensions'].isna() | (date_filtered['dimensions'] == '{}') | (date_filtered['dimensions'] == '')]
            if not no_dimensions.empty:
                date_filtered = no_dimensions
        
        # If prefer_shortest, sort by duration and take the shortest
        if prefer_shortest and 'duration' in date_filtered.columns:
            # Sort by duration (shortest first)
            date_filtered = date_filtered.sort_values('duration')
        
        # Get the first (shortest duration, non-dimensional) value
        if 'value' in date_filtered.columns:
            return date_filtered.iloc[0]['value']
        
        return None
        
    except Exception:
        return None

def extract_income_statement(filing) -> pd.DataFrame:
    """
    Extract income statement data from a SEC filing.
    
    Args:
        filing: Filing object from edgartools
        
    Returns:
        DataFrame with income statement line items and values
        
    Raises:
        ValueError: If financials cannot be extracted
    """
    # Get the XBRL data
    try:
        xbrl = filing.xbrl()
        if xbrl is None:
            raise ValueError("Unable to extract XBRL data from filing")
    except Exception as e:
        raise ValueError(f"Error accessing XBRL data: {e}")
    
    # Get the income statement using edgartools API
    try:
        # Get the income statement - use the most appropriate period
        # For 10-Q, get period views to access the quarterly (not YTD) data
        try:
            period_views = xbrl.get_period_views('income')
            
            # For 10-Q, there will be multiple periods (quarterly and YTD)
            # We want the shortest duration period (quarterly, not YTD)
            if period_views and len(period_views) > 0:
                # The first period view is typically the current/shortest period
                current_view = period_views[0]
                income_stmt = current_view.income_statement()
            else:
                # Fallback to standard method
                income_stmt = xbrl.statements.income_statement()
        except (TypeError, AttributeError):
            # If get_period_views doesn't work, use standard method
            income_stmt = xbrl.statements.income_statement()
        
        # Method 2: If that fails or returns empty, try finding by statement name
        if income_stmt is None:
            # Try to find condensed consolidated statements (common in 10-Q)
            for stmt_name in ['CONDENSEDCONSOLIDATEDSTATEMENTSOFOPERATIONSUnaudited',
                             'CONSOLIDATEDSTATEMENTSOFINCOME',
                             'CONSOLIDATEDSTATEMENTSOFOPERATIONS',
                             'StatementsOfIncome',
                             'StatementsOfOperations']:
                try:
                    income_stmt = xbrl.get_statement(stmt_name)
                    if income_stmt is not None:
                        break
                except (AttributeError, KeyError):
                    continue
        
        if income_stmt is None:
            raise ValueError("Income statement is not available")
        
        # Convert to DataFrame
        income_df = income_stmt.to_dataframe()
        
        if income_df.empty:
            raise ValueError("Income statement DataFrame is empty")
            
    except Exception as e:
        raise ValueError(f"Error retrieving income statement: {e}")
    
    print(f"✓ Retrieved income statement")
    print(f"  Shape: {income_df.shape}")
    
    # Identify date columns (columns that look like dates: YYYY-MM-DD format)
    date_columns = [
        col for col in income_df.columns 
        if isinstance(col, str) and len(col) == 10 and col[4] == '-' and col[7] == '-'
    ]
    
    if not date_columns:
        raise ValueError("No date columns found in income statement")
    
    # Sort date columns to get the most recent
    date_columns_sorted = sorted(date_columns, reverse=True)
    most_recent_period = date_columns_sorted[0]
    
    print(f"  Date columns found: {date_columns_sorted}")
    print(f"  Using most recent period: {most_recent_period}")
    print(f"  Using facts API to extract values with shortest duration...")
    
    # Extract line items using facts API (ensures shortest duration for 10-Q)
    results = []
    
    for line_item, concept_list in INCOME_STATEMENT_MAPPING.items():
        value = None
        matched_concept = None
        
        # Try each concept in the list
        for concept in concept_list:
            # Build the full concept name (us-gaap prefix)
            full_concept = f"us-gaap_{concept}"
            
            # Query using facts API with shortest duration preference
            fact_value = get_fact_value(xbrl, full_concept, most_recent_period, prefer_shortest=True)
            
            if fact_value is not None:
                matched_concept = full_concept
                value = fact_value
                break
        
        results.append({
            'Line Item': line_item,
            'Value': value,
            'XBRL Concept': matched_concept,
        })
    
    # Convert to DataFrame
    result_df = (
        pd.DataFrame(results)
        .pipe(lambda df: df.assign(
            Value=pd.to_numeric(df['Value'], errors='coerce')
        ))
    )
    
    found_count = result_df['Value'].notna().sum()
    total_count = len(result_df)
    
    print(f"✓ Extracted {found_count}/{total_count} line items")
    
    return result_df

# Test with the previously retrieved filing
test_income_stmt = extract_income_statement(test_filing)
print(f"\n✓ Test successful")
test_income_stmt.head(10)

✓ Retrieved income statement
  Shape: (42, 19)
  Date columns found: ['2023-09-30', '2022-09-24', '2021-09-25']
  Using most recent period: 2023-09-30
  Using facts API to extract values with shortest duration...
✓ Extracted 18/23 line items

✓ Test successful

,Line Item,Value,XBRL Concept
0,Revenue,2.980850e+11,us-gaap_RevenueFromContractWithCustomerExcludi...
1,Cost of Revenue,1.892820e+11,us-gaap_CostOfGoodsAndServicesSold
2,Gross Profit,1.691480e+11,us-gaap_GrossProfit
3,Research & Development,2.991500e+10,us-gaap_ResearchAndDevelopmentExpense
4,"Selling, General & Administrative",2.493200e+10,us-gaap_SellingGeneralAndAdministrativeExpense
5,Depreciation & Amortization,1.151900e+10,us-gaap_DepreciationDepletionAndAmortization
6,Other Operating Expenses,NaN,NaN
7,Operating Income,6.050800e+10,us-gaap_OperatingIncomeLoss
8,Interest Income,3.750000e+09,us-gaap_InvestmentIncomeInterest
9,Interest Expense,3.933000e+09,us-gaap_InterestExpense

## 4.5 Diagnostic - Explore XBRL Structure (Run if errors occur)

Use this cell to understand the structure of the XBRL data.

In [104]:
# Diagnostic: Explore the XBRL object structure
print("=== XBRL Object Exploration ===\n")

xbrl = test_filing.xbrl()
print(f"XBRL object type: {type(xbrl)}")
print(f"XBRL object: {xbrl}\n")

print("Available attributes and methods (non-private):")
attrs = [attr for attr in dir(xbrl) if not attr.startswith('_')]
for attr in attrs:
    attr_type = type(getattr(xbrl, attr, None)).__name__
    print(f"  - {attr:<30} ({attr_type})")

# Try common financial statement accessors
print("\n" + "="*50)
print("Trying common accessors:")
print("="*50)

# Try: statements
if hasattr(xbrl, 'statements'):
    print("\n✓ xbrl.statements found:")
    try:
        stmts = xbrl.statements
        print(f"  Type: {type(stmts)}")
        if hasattr(stmts, '__iter__'):
            for stmt in stmts:
                print(f"  - {stmt}")
    except Exception as e:
        print(f"  Error: {e}")

# Try: get_statement method
if hasattr(xbrl, 'get_statement'):
    print("\n✓ xbrl.get_statement() method found")

# Try: income_statement property
for prop_name in ['income_statement', 'income', 'IncomeStatement']:
    if hasattr(xbrl, prop_name):
        print(f"\n✓ xbrl.{prop_name} found:")
        try:
            stmt = getattr(xbrl, prop_name)
            print(f"  Type: {type(stmt)}")
            if isinstance(stmt, pd.DataFrame):
                print(f"  Shape: {stmt.shape}")
                print(f"  Columns: {list(stmt.columns)}")
                print(f"\n  First few rows:")
                print(stmt.head())
        except Exception as e:
            print(f"  Error: {e}")

# Try: facts
if hasattr(xbrl, 'facts'):
    print("\n✓ xbrl.facts found:")
    try:
        facts = xbrl.facts
        print(f"  Type: {type(facts)}")
        if isinstance(facts, pd.DataFrame):
            print(f"  Shape: {facts.shape}")
            print(f"  Columns: {list(facts.columns)}")
            # Show sample revenue-related facts
            if 'concept' in facts.columns:
                revenue_facts = facts[facts['concept'].str.contains('Revenue', case=False, na=False)]
                print(f"\n  Sample Revenue concepts found: {len(revenue_facts)}")
                if not revenue_facts.empty:
                    print(revenue_facts.head())
    except Exception as e:
        print(f"  Error: {e}")

print("\n" + "="*50)

=== XBRL Object Exploration ===

XBRL object type: <class 'edgar.xbrl.xbrl.XBRL'>

XBRL object: ╭───────────────────────────────────────────────── XBRL Document ─────────────────────────────────────────────────╮
│ Apple Inc. (AAPL) • CIK 0000320193                                                                              │
│                                                                                                                 │
│          Form:  10-K                                                                                            │
│ Fiscal Period:  Fiscal Year 2023 (ended Sep 30, 2023)                                                           │
│          Data:  1,164 facts • 205 contexts                                                                      │
│                                                                                                                 │
│ Periods Available for Statements:                                                                               │
│   Annual: FY 2023, FY 2022, FY 2021                                                                             │
│   Quarterly: July 02, 2023 to September 30, 2023                                                                │
│   (1 future period after 2023-09-30 excluded)                                                                   │
│                                                                                                                 │
│ Common Actions                                                                                                  │
│ ────────────────────────────────────────────────────────────                                                    │
│ # List all available statements                                                                                 │
│   xbrl.statements                                                                                               │
│                                                                                                                 │
│ # Access statements by name or index                                                                            │
│   stmt = xbrl.statements['CoverPage']                                                                           │
│   stmt = xbrl.statements[6]                                                                                     │
│                                                                                                                 │
│ # View core financial statements                                                                                │
│   stmt = xbrl.statements.income_statement()                                                                     │
│   stmt = xbrl.statements.balance_sheet()                                                                        │
│   stmt = xbrl.statements.cash_flow_statement()                                                                  │
│   stmt = xbrl.statements.statement_of_equity()                                                                  │
│   stmt = xbrl.statements.comprehensive_income()                                                                 │
│                                                                                                                 │
│ # Get current period only                                                                                       │
│   current = xbrl.current_period                                                                                 │
│   stmt = current.income_statement()                                                                             │
│                                                                                                                 │
│ # Convert statement to DataFrame                                                                                │
│   df = stmt.to_dataframe()                                                                                      │
│                                                                                                                 │
│ # Query specific facts                                                                                          │
│   revenue = xbrl.facts.query().by_concept('Revenue').to_dataframe()                                             │
│                                                                                                                 │
│ 💡 Tip: Use xbrl.docs for comprehensive usage guide                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯


Available attributes and methods (non-private):
  - axes                           (dict)
  - calculation_roles              (dict)
  - calculation_trees              (dict)
  - context_period_map             (dict)
  - contexts                       (dict)
  - current_period                 (CurrentPeriodView)
  - definition_roles               (dict)
  - docs                           (Docs)
  - document_type                  (str)
  - domains                        (dict)
  - element_catalog                (dict)
  - entity_info                    (dict)
  - entity_name                    (str)
  - facts                          (FactsView)
  - find_statement                 (method)
  - footnotes                      (dict)
  - from_directory                 (method)
  - from_files                     (method)
  - from_filing                    (method)
  - fund_statements                (FundStatements)
  - get_all_statements             (method)
  - get_currency_for_fact          (method)
  - get_facts_with_footnotes       (method)
  - get_footnotes_for_fact         (method)
  - get_period_views               (method)
  - get_statement                  (method)
  - get_statement_by_type          (method)
  - get_statements_by_category     (method)
  - get_valid_dimensions_for_role  (method)
  - has_definition_linkbase_for_role (method)
  - is_dimension_valid_for_role    (method)
  - parser                         (XBRLParser)
  - period_of_report               (str)
  - presentation_roles             (dict)
  - presentation_trees             (dict)
  - query                          (method)
  - render_statement               (method)
  - render_stitched_statement      (method)
  - reporting_periods              (list)
  - standardization                (StandardizationCache)
  - statements                     (Statements)
  - stitch_statements              (method)
  - tables                         (dict)
  - text                           (method)
  - to_context                     (method)
  - to_pandas                      (method)
  - units                          (dict)

==================================================
Trying common accessors:
==================================================

✓ xbrl.statements found:
  Type: <class 'edgar.xbrl.statements.Statements'>

✓ xbrl.get_statement() method found

✓ xbrl.facts found:
  Type: <class 'edgar.xbrl.facts.FactsView'>

==================================================

## 4.6 Diagnostic - View Raw Income Statement Data

Use this cell to see the actual data structure and verify values.

In [105]:
# Diagnostic: View the raw income statement data
xbrl = filing.xbrl()
income_stmt = xbrl.statements.income_statement()
income_df = income_stmt.to_dataframe()

print("="*80)
print("ALL COLUMNS IN INCOME STATEMENT:")
print("="*80)
print(f"Shape: {income_df.shape}")
print(f"\nAll columns: {list(income_df.columns)}")

# Show all rows with a few key columns
print("\n" + "="*80)
print("INCOME STATEMENT DATA (showing first 50 rows):")
print("="*80)

# Select columns to display
display_cols = ['concept', 'label']
# Add all date-like columns
date_cols = [col for col in income_df.columns 
             if isinstance(col, str) and len(col) == 10 and col[4] == '-' and col[7] == '-']
display_cols.extend(date_cols)

print(f"\nDate columns found: {date_cols}")
print("\n")

# Display the data
income_df[display_cols].head(50)

================================================================================
ALL COLUMNS IN INCOME STATEMENT:
================================================================================
Shape: (39, 18)

All columns: ['concept', 'label', 'standard_concept', '2025-06-28', '2024-06-29', 'level', 'abstract', 'dimension', 'is_breakdown', 'dimension_axis', 'dimension_member', 'dimension_member_label', 'dimension_label', 'balance', 'weight', 'preferred_sign', 'parent_concept', 'parent_abstract_concept']

================================================================================
INCOME STATEMENT DATA (showing first 50 rows):
================================================================================

Date columns found: ['2025-06-28', '2024-06-29']

,concept,label,2025-06-28,2024-06-29
0,us-gaap_RevenueFromContractWithCustomerExcludi...,Net sales,3.136950e+11,2.961050e+11
1,us-gaap_RevenueFromContractWithCustomerExcludi...,Products,2.332870e+11,2.249080e+11
2,us-gaap_RevenueFromContractWithCustomerExcludi...,Services,8.040800e+10,7.119700e+10
3,us-gaap_RevenueFromContractWithCustomerExcludi...,iPhone,1.605610e+11,1.549610e+11
4,us-gaap_RevenueFromContractWithCustomerExcludi...,Mac,2.498200e+10,2.224000e+10
5,us-gaap_RevenueFromContractWithCustomerExcludi...,iPad,2.107100e+10,1.974400e+10
6,us-gaap_RevenueFromContractWithCustomerExcludi...,"Wearables, Home and Accessories",2.667300e+10,2.796300e+10
7,us-gaap_RevenueFromContractWithCustomerExcludi...,Americas,1.341610e+11,1.253810e+11
8,us-gaap_RevenueFromContractWithCustomerExcludi...,Europe,8.232900e+10,7.640400e+10
9,us-gaap_RevenueFromContractWithCustomerExcludi...,Greater China,4.988400e+10,5.191900e+10
10,us-gaap_RevenueFromContractWithCustomerExcludi...,Japan,2.206700e+10,1.912600e+10
11,us-gaap_RevenueFromContractWithCustomerExcludi...,Rest of Asia Pacific,2.525400e+10,2.327500e+10
12,us-gaap_CostOfGoodsAndServicesSold,Cost of sales,1.668350e+11,1.593010e+11
13,us-gaap_CostOfGoodsAndServicesSold,Products,1.470970e+11,1.406670e+11
14,us-gaap_CostOfGoodsAndServicesSold,Services,1.973800e+10,1.863400e+10
15,us-gaap_GrossProfit,Gross margin,1.468600e+11,1.368040e+11
16,us-gaap_OperatingExpensesAbstract,Operating expenses:,NaN,NaN
17,us-gaap_ResearchAndDevelopmentExpense,Research and development,2.568400e+10,2.360500e+10
18,us-gaap_ResearchAndDevelopmentExpense,Segment reconciling items,2.568400e+10,2.360500e+10
19,us-gaap_SellingGeneralAndAdministrativeExpense,"Selling, general and administrative",2.055300e+10,1.957400e+10
20,us-gaap_OperatingExpenses,Total operating expenses,4.623700e+10,4.317900e+10
21,us-gaap_OperatingIncomeLoss,Operating income,1.006230e+11,9.362500e+10
22,us-gaap_OperatingIncomeLoss,Americas,5.479400e+10,5.064000e+10
23,us-gaap_OperatingIncomeLoss,Europe,3.542400e+10,3.187200e+10
24,us-gaap_OperatingIncomeLoss,Greater China,2.060800e+10,2.088400e+10
25,us-gaap_OperatingIncomeLoss,Japan,1.062000e+10,9.498000e+09
26,us-gaap_OperatingIncomeLoss,Rest of Asia Pacific,1.081300e+10,9.995000e+09
27,us-gaap_OperatingIncomeLoss,Operating segments,1.322590e+11,1.228890e+11
28,us-gaap_NonoperatingIncomeExpense,"Other income/(expense), net",-6.980000e+08,2.500000e+08
29,us-gaap_IncomeLossFromContinuingOperationsBefo...,Income before provision for income taxes,9.992500e+10,9.387500e+10
30,us-gaap_IncomeTaxExpenseBenefit,Provision for income taxes,1.538100e+10,1.487500e+10
31,us-gaap_NetIncomeLoss,Net income,8.454400e+10,7.900000e+10
32,us-gaap_NetIncomeLoss,Retained earnings/(Accumulated deficit),8.454400e+10,7.900000e+10
33,us-gaap_EarningsPerShareAbstract,Earnings per share:,NaN,NaN
34,us-gaap_EarningsPerShareBasic,Basic (in dollars per share),5.640000e+00,5.130000e+00
35,us-gaap_EarningsPerShareDiluted,Diluted (in dollars per share),5.620000e+00,5.110000e+00
36,us-gaap_WeightedAverageNumberOfSharesOutstandi...,Shares used in computing earnings per share:,NaN,NaN
37,us-gaap_WeightedAverageNumberOfSharesOutstandi...,Basic (in shares),1.499290e+10,1.540105e+10
38,us-gaap_WeightedAverageNumberOfDilutedSharesOu...,Diluted (in shares),1.505173e+10,1.546318e+10

## 5. User Interface - Get Income Statement

Configure the parameters below to retrieve the income statement for your desired company and period.

In [110]:
# ===== USER CONFIGURATION =====
# Modify these parameters to get the income statement you need

TICKER = "AAPL"           # Company ticker symbol
FILING_TYPE = "10-Q"      # "10-K" for annual, "10-Q" for quarterly
YEAR = 2025            # Fiscal year (set to None for most recent)
QUARTER = 2              # Fiscal quarter 1-4 (only for 10-Q, set to None for most recent)

# ===== END USER CONFIGURATION =====

print("Configuration:")
print(f"  Ticker: {TICKER}")
print(f"  Filing Type: {FILING_TYPE}")
print(f"  Year: {YEAR if YEAR else 'Most Recent'}")
if FILING_TYPE == "10-Q":
    print(f"  Quarter: Q{QUARTER if QUARTER else 'Most Recent'}")

Configuration:
  Ticker: AAPL
  Filing Type: 10-Q
  Year: 2025
  Quarter: Q2

In [111]:
# Retrieve the filing
filing = get_filing(
    ticker=TICKER,
    filing_type=FILING_TYPE,
    year=YEAR,
    quarter=QUARTER
)

# Extract the income statement
income_statement_df = extract_income_statement(filing)

# Display results
print("\n" + "="*80)
print("INCOME STATEMENT")
print("="*80)
income_statement_df

2026-01-29 06:15:46,152 - INFO - No cache policy for data.sec.gov:///submissions/CIK0000320193.json, not retrieving from cache
2026-01-29 06:15:46,153 - INFO - Making HTTP Request <Request('GET', 'https://data.sec.gov/submissions/CIK0000320193.json')>
2026-01-29 06:15:46,357 - INFO - HTTP Request: GET https://data.sec.gov/submissions/CIK0000320193.json "HTTP/1.1 200 OK"
2026-01-29 06:15:46,384 - INFO - No cache policy for data.sec.gov:///submissions/CIK0000320193-submissions-001.json, not retrieving from cache
2026-01-29 06:15:46,384 - INFO - Making HTTP Request <Request('GET', 'https://data.sec.gov/submissions/CIK0000320193-submissions-001.json')>
2026-01-29 06:15:46,528 - INFO - HTTP Request: GET https://data.sec.gov/submissions/CIK0000320193-submissions-001.json "HTTP/1.1 200 OK"
2026-01-29 06:15:46,537 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:15:46,537 - INFO - /Archives/edgar/data/320193/000032019325000073/0000320193-25-000073.txt matched /Archives/edgar/data, using value True
2026-01-29 06:15:46,538 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000032019325000073-0000320193-25-000073.txt
2026-01-29 06:15:46,545 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000032019325000073/0000320193-25-000073.txt "HTTP/1.1 200 OK"
2026-01-29 06:15:46,573 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:15:46,573 - INFO - /Archives/edgar/data/320193/000032019325000057/0000320193-25-000057.txt matched /Archives/edgar/data, using value True
2026-01-29 06:15:46,575 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000032019325000057-0000320193-25-000057.txt
2026-01-29 06:15:46,582 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000032019325000057/0000320193-25-000057.txt "HTTP/1.1 200 OK"

✓ Retrieved company: Apple Inc. (AAPL)

2026-01-29 06:15:46,610 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:15:46,611 - INFO - /Archives/edgar/data/320193/000032019325000008/0000320193-25-000008.txt matched /Archives/edgar/data, using value True
2026-01-29 06:15:46,613 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000032019325000008-0000320193-25-000008.txt
2026-01-29 06:15:46,621 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000032019325000008/0000320193-25-000008.txt "HTTP/1.1 200 OK"
2026-01-29 06:15:46,669 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:15:46,670 - INFO - /Archives/edgar/data/320193/000032019324000081/0000320193-24-000081.txt matched /Archives/edgar/data, using value True
2026-01-29 06:15:46,671 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000032019324000081-0000320193-24-000081.txt
2026-01-29 06:15:46,679 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000032019324000081/0000320193-24-000081.txt "HTTP/1.1 200 OK"
2026-01-29 06:15:46,732 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:15:46,732 - INFO - /Archives/edgar/data/320193/000032019324000069/0000320193-24-000069.txt matched /Archives/edgar/data, using value True
2026-01-29 06:15:46,734 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000032019324000069-0000320193-24-000069.txt
2026-01-29 06:15:46,742 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000032019324000069/0000320193-24-000069.txt "HTTP/1.1 200 OK"
2026-01-29 06:15:46,773 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:15:46,773 - INFO - /Archives/edgar/data/320193/000032019324000006/0000320193-24-000006.txt matched /Archives/edgar/data, using value True
2026-01-29 06:15:46,774 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000032019324000006-0000320193-24-000006.txt
2026-01-29 06:15:46,782 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000032019324000006/0000320193-24-000006.txt "HTTP/1.1 200 OK"
2026-01-29 06:15:46,814 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:15:46,814 - INFO - /Archives/edgar/data/320193/000032019323000077/0000320193-23-000077.txt matched /Archives/edgar/data, using value True
2026-01-29 06:15:46,815 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000032019323000077-0000320193-23-000077.txt
2026-01-29 06:15:46,849 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000032019323000077/0000320193-23-000077.txt "HTTP/1.1 200 OK"
2026-01-29 06:15:46,891 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:15:46,891 - INFO - /Archives/edgar/data/320193/000032019323000064/0000320193-23-000064.txt matched /Archives/edgar/data, using value True
2026-01-29 06:15:46,893 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000032019323000064-0000320193-23-000064.txt
2026-01-29 06:15:46,902 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000032019323000064/0000320193-23-000064.txt "HTTP/1.1 200 OK"
2026-01-29 06:15:46,957 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:15:46,957 - INFO - /Archives/edgar/data/320193/000032019323000006/0000320193-23-000006.txt matched /Archives/edgar/data, using value True
2026-01-29 06:15:46,960 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000032019323000006-0000320193-23-000006.txt
2026-01-29 06:15:46,987 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000032019323000006/0000320193-23-000006.txt "HTTP/1.1 200 OK"
2026-01-29 06:15:47,017 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:15:47,018 - INFO - /Archives/edgar/data/320193/000032019322000070/0000320193-22-000070.txt matched /Archives/edgar/data, using value True
2026-01-29 06:15:47,019 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000032019322000070-0000320193-22-000070.txt
2026-01-29 06:15:47,040 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000032019322000070/0000320193-22-000070.txt "HTTP/1.1 200 OK"
2026-01-29 06:15:47,072 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:15:47,073 - INFO - /Archives/edgar/data/320193/000032019322000059/0000320193-22-000059.txt matched /Archives/edgar/data, using value True
2026-01-29 06:15:47,073 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000032019322000059-0000320193-22-000059.txt
2026-01-29 06:15:47,082 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000032019322000059/0000320193-22-000059.txt "HTTP/1.1 200 OK"
2026-01-29 06:15:47,149 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:15:47,149 - INFO - /Archives/edgar/data/320193/000032019322000007/0000320193-22-000007.txt matched /Archives/edgar/data, using value True
2026-01-29 06:15:47,151 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000032019322000007-0000320193-22-000007.txt
2026-01-29 06:15:47,161 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000032019322000007/0000320193-22-000007.txt "HTTP/1.1 200 OK"
2026-01-29 06:15:47,191 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:15:47,191 - INFO - /Archives/edgar/data/320193/000032019321000065/0000320193-21-000065.txt matched /Archives/edgar/data, using value True
2026-01-29 06:15:47,192 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000032019321000065-0000320193-21-000065.txt
2026-01-29 06:15:47,217 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000032019321000065/0000320193-21-000065.txt "HTTP/1.1 200 OK"
2026-01-29 06:15:47,275 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:15:47,275 - INFO - /Archives/edgar/data/320193/000032019321000056/0000320193-21-000056.txt matched /Archives/edgar/data, using value True
2026-01-29 06:15:47,279 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000032019321000056-0000320193-21-000056.txt
2026-01-29 06:15:47,296 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000032019321000056/0000320193-21-000056.txt "HTTP/1.1 200 OK"
2026-01-29 06:15:47,342 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:15:47,343 - INFO - /Archives/edgar/data/320193/000032019321000010/0000320193-21-000010.txt matched /Archives/edgar/data, using value True
2026-01-29 06:15:47,344 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000032019321000010-0000320193-21-000010.txt
2026-01-29 06:15:47,359 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000032019321000010/0000320193-21-000010.txt "HTTP/1.1 200 OK"
2026-01-29 06:15:47,423 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:15:47,424 - INFO - /Archives/edgar/data/320193/000032019320000062/0000320193-20-000062.txt matched /Archives/edgar/data, using value True
2026-01-29 06:15:47,425 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000032019320000062-0000320193-20-000062.txt
2026-01-29 06:15:47,466 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000032019320000062/0000320193-20-000062.txt "HTTP/1.1 200 OK"
2026-01-29 06:15:47,515 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:15:47,516 - INFO - /Archives/edgar/data/320193/000032019320000052/0000320193-20-000052.txt matched /Archives/edgar/data, using value True
2026-01-29 06:15:47,518 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000032019320000052-0000320193-20-000052.txt
2026-01-29 06:15:47,547 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000032019320000052/0000320193-20-000052.txt "HTTP/1.1 200 OK"
2026-01-29 06:15:47,609 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:15:47,610 - INFO - /Archives/edgar/data/320193/000032019320000010/0000320193-20-000010.txt matched /Archives/edgar/data, using value True
2026-01-29 06:15:47,611 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000032019320000010-0000320193-20-000010.txt
2026-01-29 06:15:47,639 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000032019320000010/0000320193-20-000010.txt "HTTP/1.1 200 OK"
2026-01-29 06:15:47,695 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:15:47,695 - INFO - /Archives/edgar/data/320193/000032019319000076/0000320193-19-000076.txt matched /Archives/edgar/data, using value True
2026-01-29 06:15:47,697 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000032019319000076-0000320193-19-000076.txt
2026-01-29 06:15:47,737 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000032019319000076/0000320193-19-000076.txt "HTTP/1.1 200 OK"
2026-01-29 06:15:47,782 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:15:47,783 - INFO - /Archives/edgar/data/320193/000032019319000066/0000320193-19-000066.txt matched /Archives/edgar/data, using value True
2026-01-29 06:15:47,785 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000032019319000066-0000320193-19-000066.txt
2026-01-29 06:15:47,812 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000032019319000066/0000320193-19-000066.txt "HTTP/1.1 200 OK"
2026-01-29 06:15:47,894 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:15:47,895 - INFO - /Archives/edgar/data/320193/000032019319000010/0000320193-19-000010.txt matched /Archives/edgar/data, using value True
2026-01-29 06:15:47,896 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000032019319000010-0000320193-19-000010.txt
2026-01-29 06:15:47,908 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000032019319000010/0000320193-19-000010.txt "HTTP/1.1 200 OK"
2026-01-29 06:15:47,943 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:15:47,943 - INFO - /Archives/edgar/data/320193/000032019318000100/0000320193-18-000100.txt matched /Archives/edgar/data, using value True
2026-01-29 06:15:47,944 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000032019318000100-0000320193-18-000100.txt
2026-01-29 06:15:47,958 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000032019318000100/0000320193-18-000100.txt "HTTP/1.1 200 OK"
2026-01-29 06:15:48,024 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:15:48,025 - INFO - /Archives/edgar/data/320193/000032019318000070/0000320193-18-000070.txt matched /Archives/edgar/data, using value True
2026-01-29 06:15:48,026 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000032019318000070-0000320193-18-000070.txt
2026-01-29 06:15:48,065 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000032019318000070/0000320193-18-000070.txt "HTTP/1.1 200 OK"
2026-01-29 06:15:48,101 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:15:48,102 - INFO - /Archives/edgar/data/320193/000032019318000007/0000320193-18-000007.txt matched /Archives/edgar/data, using value True
2026-01-29 06:15:48,103 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000032019318000007-0000320193-18-000007.txt
2026-01-29 06:15:48,130 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000032019318000007/0000320193-18-000007.txt "HTTP/1.1 200 OK"
2026-01-29 06:15:48,166 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:15:48,167 - INFO - /Archives/edgar/data/320193/000032019317000009/0000320193-17-000009.txt matched /Archives/edgar/data, using value True
2026-01-29 06:15:48,168 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000032019317000009-0000320193-17-000009.txt
2026-01-29 06:15:48,184 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000032019317000009/0000320193-17-000009.txt "HTTP/1.1 200 OK"
2026-01-29 06:15:48,251 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:15:48,251 - INFO - /Archives/edgar/data/320193/000162828017004790/0001628280-17-004790.txt matched /Archives/edgar/data, using value True
2026-01-29 06:15:48,254 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000162828017004790-0001628280-17-004790.txt
2026-01-29 06:15:48,277 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000162828017004790/0001628280-17-004790.txt "HTTP/1.1 200 OK"
2026-01-29 06:15:48,346 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:15:48,347 - INFO - /Archives/edgar/data/320193/000162828017000717/0001628280-17-000717.txt matched /Archives/edgar/data, using value True
2026-01-29 06:15:48,348 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000162828017000717-0001628280-17-000717.txt
2026-01-29 06:15:48,386 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000162828017000717/0001628280-17-000717.txt "HTTP/1.1 200 OK"
2026-01-29 06:15:48,417 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:15:48,418 - INFO - /Archives/edgar/data/320193/000162828016017809/0001628280-16-017809.txt matched /Archives/edgar/data, using value True
2026-01-29 06:15:48,420 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000162828016017809-0001628280-16-017809.txt
2026-01-29 06:15:48,449 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000162828016017809/0001628280-16-017809.txt "HTTP/1.1 200 OK"
2026-01-29 06:15:48,510 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}
2026-01-29 06:15:48,511 - INFO - /Archives/edgar/data/320193/000119312516559625/0001193125-16-559625.txt matched /Archives/edgar/data, using value True
2026-01-29 06:15:48,513 - INFO - Cache policy allows unlimited cache, returning /home/pedro/.edgar/_tcache/www.sec.gov/Archives-edgar-data-320193-000119312516559625-0001193125-16-559625.txt
2026-01-29 06:15:48,521 - INFO - HTTP Request: GET https://www.sec.gov/Archives/edgar/data/320193/000119312516559625/0001193125-16-559625.txt "HTTP/1.1 200 OK"
2026-01-29 06:15:48,574 - INFO - matched .*www\.sec\.gov, using value www.sec.gov: {'/submissions.*': 30, '/include/ticker\\.txt.*': 30, '/files/company_tickers\\.json.*': 30, '.*index/.*': 1800, '/Archives/edgar/data': True}

✓ Retrieved 10-Q filing
  Filing Date: 2025-08-01
  Period of Report: 2025-06-28
✓ Retrieved income statement
  Shape: (39, 18)
  Date columns found: ['2025-06-28', '2024-06-29']
  Using most recent period: 2025-06-28
  Using facts API to extract values with shortest duration...
✓ Extracted 16/23 line items

================================================================================
INCOME STATEMENT
================================================================================

,Line Item,Value,XBRL Concept
0,Revenue,6.661300e+10,us-gaap_RevenueFromContractWithCustomerExcludi...
1,Cost of Revenue,4.362000e+10,us-gaap_CostOfGoodsAndServicesSold
2,Gross Profit,4.371800e+10,us-gaap_GrossProfit
3,Research & Development,8.866000e+09,us-gaap_ResearchAndDevelopmentExpense
4,"Selling, General & Administrative",6.650000e+09,us-gaap_SellingGeneralAndAdministrativeExpense
5,Depreciation & Amortization,8.571000e+09,us-gaap_DepreciationDepletionAndAmortization
6,Other Operating Expenses,NaN,NaN
7,Operating Income,1.651100e+10,us-gaap_OperatingIncomeLoss
8,Interest Income,NaN,NaN
9,Interest Expense,NaN,NaN
10,Other Income/Expense,-1.710000e+08,us-gaap_NonoperatingIncomeExpense
11,Gains/Losses on Investments,NaN,NaN
12,Pretax Income,2.803100e+10,us-gaap_IncomeLossFromContinuingOperationsBefo...
13,Income Tax Expense,4.597000e+09,us-gaap_IncomeTaxExpenseBenefit
14,Net Income from Continuing Operations,2.803100e+10,us-gaap_IncomeLossFromContinuingOperations
15,Discontinued Operations,NaN,NaN
16,Net Income,2.343400e+10,us-gaap_NetIncomeLoss
17,Net Income Attributable to Noncontrolling Inte...,NaN,NaN
18,Net Income Attributable to Common Shareholders,NaN,NaN
19,Basic EPS,1.570000e+00,us-gaap_EarningsPerShareBasic
20,Diluted EPS,1.570000e+00,us-gaap_EarningsPerShareDiluted
21,Basic Weighted Average Shares Outstanding,1.490289e+10,us-gaap_WeightedAverageNumberOfSharesOutstandi...
22,Diluted Weighted Average Shares Outstanding,1.494818e+10,us-gaap_WeightedAverageNumberOfDilutedSharesOu...

## 6. Format and Display Results

Format the income statement for better readability with proper currency formatting.

In [98]:
def format_income_statement(df: pd.DataFrame) -> pd.DataFrame:
    """
    Format income statement for better display.
    
    Args:
        df: DataFrame with income statement data
        
    Returns:
        Formatted DataFrame with styled values
    """
    formatted_df = (
        df
        .copy()
        .assign(
            # Format values as currency (assuming values are in dollars)
            Formatted_Value=lambda x: x['Value'].apply(
                lambda v: f"${v:,.0f}" if pd.notna(v) else "Not Found"
            ),
            # Add status indicator
            Status=lambda x: x['Value'].apply(
                lambda v: "✓" if pd.notna(v) else "✗"
            )
        )
        # Select and reorder columns
        [['Status', 'Line Item', 'Formatted_Value', 'XBRL Concept']]
        .rename(columns={'Formatted_Value': 'Value'})
    )
    
    return formatted_df

# Format the income statement
formatted_income_statement = format_income_statement(income_statement_df)

# Display with better formatting
print(f"\n{'='*100}")
print(f"INCOME STATEMENT - {TICKER}")
print(f"Filing Type: {FILING_TYPE} | Year: {YEAR if YEAR else 'Most Recent'}")
print(f"{'='*100}\n")

formatted_income_statement

====================================================================================================
INCOME STATEMENT - AAPL
Filing Type: 10-Q | Year: 2025
====================================================================================================

,Status,Line Item,Value,XBRL Concept
0,✓,Revenue,"$313,695,000,000",us-gaap_RevenueFromContractWithCustomerExcludi...
1,✓,Cost of Revenue,"$166,835,000,000",us-gaap_CostOfGoodsAndServicesSold
2,✓,Gross Profit,"$146,860,000,000",us-gaap_GrossProfit
3,✓,Research & Development,"$25,684,000,000",us-gaap_ResearchAndDevelopmentExpense
4,✓,"Selling, General & Administrative","$20,553,000,000",us-gaap_SellingGeneralAndAdministrativeExpense
5,✗,Depreciation & Amortization,Not Found,NaN
6,✗,Other Operating Expenses,Not Found,NaN
7,✓,Operating Income,"$100,623,000,000",us-gaap_OperatingIncomeLoss
8,✗,Interest Income,Not Found,NaN
9,✗,Interest Expense,Not Found,NaN
10,✓,Other Income/Expense,"$-698,000,000",us-gaap_NonoperatingIncomeExpense
11,✗,Gains/Losses on Investments,Not Found,NaN
12,✓,Pretax Income,"$99,925,000,000",us-gaap_IncomeLossFromContinuingOperationsBefo...
13,✓,Income Tax Expense,"$15,381,000,000",us-gaap_IncomeTaxExpenseBenefit
14,✓,Net Income from Continuing Operations,"$99,925,000,000",us-gaap_IncomeLossFromContinuingOperationsBefo...
15,✗,Discontinued Operations,Not Found,NaN
16,✓,Net Income,"$84,544,000,000",us-gaap_NetIncomeLoss
17,✗,Net Income Attributable to Noncontrolling Inte...,Not Found,NaN
18,✗,Net Income Attributable to Common Shareholders,Not Found,NaN
19,✓,Basic EPS,$6,us-gaap_EarningsPerShareBasic
20,✓,Diluted EPS,$6,us-gaap_EarningsPerShareDiluted
21,✓,Basic Weighted Average Shares Outstanding,"$14,992,898,000",us-gaap_WeightedAverageNumberOfSharesOutstandi...
22,✓,Diluted Weighted Average Shares Outstanding,"$15,051,726,000",us-gaap_WeightedAverageNumberOfDilutedSharesOu...

## 7. Validation Summary

Check which required line items were found and which are missing.

In [50]:
def validate_income_statement(df: pd.DataFrame) -> dict:
    """
    Validate income statement completeness.
    
    Args:
        df: DataFrame with income statement data
        
    Returns:
        Dictionary with validation statistics
    """
    total_items = len(df)
    found_items = df['Value'].notna().sum()
    missing_items = total_items - found_items
    completeness_pct = (found_items / total_items) * 100 if total_items > 0 else 0
    
    missing_line_items = df[df['Value'].isna()]['Line Item'].tolist()
    
    return {
        'total_items': total_items,
        'found_items': found_items,
        'missing_items': missing_items,
        'completeness_percentage': completeness_pct,
        'missing_line_items': missing_line_items
    }

# Validate the income statement
validation_results = validate_income_statement(income_statement_df)

print("\n" + "="*80)
print("VALIDATION SUMMARY")
print("="*80)
print(f"Total Line Items:        {validation_results['total_items']}")
print(f"Found:                   {validation_results['found_items']} ✓")
print(f"Missing:                 {validation_results['missing_items']} ✗")
print(f"Completeness:            {validation_results['completeness_percentage']:.1f}%")

if validation_results['missing_line_items']:
    print("\nMissing Line Items:")
    for item in validation_results['missing_line_items']:
        print(f"  - {item}")
else:
    print("\n✓ All required line items found!")

print("="*80)

================================================================================
VALIDATION SUMMARY
================================================================================
Total Line Items:        23
Found:                   15 ✓
Missing:                 8 ✗
Completeness:            65.2%

Missing Line Items:
  - Depreciation & Amortization
  - Other Operating Expenses
  - Interest Income
  - Interest Expense
  - Gains/Losses on Investments
  - Discontinued Operations
  - Net Income Attributable to Noncontrolling Interests
  - Net Income Attributable to Common Shareholders
================================================================================

## 8. Export Data (Optional)

Export the income statement to CSV for further analysis.

In [ ]:
# Optional: Export to CSV
EXPORT_TO_CSV = False  # Set to True to enable export
OUTPUT_FILENAME = f"{TICKER}_{FILING_TYPE}_{YEAR}_income_statement.csv"

if EXPORT_TO_CSV:
    output_path = Path(OUTPUT_FILENAME)
    income_statement_df.to_csv(output_path, index=False)
    print(f"✓ Income statement exported to: {output_path.absolute()}")
else:
    print("Export disabled. Set EXPORT_TO_CSV = True to enable.")

## 9. Examples and Usage Patterns

Here are some common usage examples you can copy and modify.

In [ ]:
# EXAMPLE 1: Get most recent 10-K for Apple
# filing_ex1 = get_filing("AAPL", "10-K")
# income_ex1 = extract_income_statement(filing_ex1)

# EXAMPLE 2: Get specific year 10-K for Microsoft
# filing_ex2 = get_filing("MSFT", "10-K", year=2022)
# income_ex2 = extract_income_statement(filing_ex2)

# EXAMPLE 3: Get most recent 10-Q for Tesla
# filing_ex3 = get_filing("TSLA", "10-Q")
# income_ex3 = extract_income_statement(filing_ex3)

# EXAMPLE 4: Get specific quarter 10-Q for Amazon
# filing_ex4 = get_filing("AMZN", "10-Q", year=2023, quarter=2)
# income_ex4 = extract_income_statement(filing_ex4)

# EXAMPLE 5: Compare multiple quarters
# quarters_data = []
# for q in [1, 2, 3, 4]:
#     try:
#         filing = get_filing("GOOGL", "10-Q", year=2023, quarter=q)
#         income = extract_income_statement(filing)
#         income['Quarter'] = f"Q{q}"
#         quarters_data.append(income)
#     except FileNotFoundError:
#         print(f"Q{q} not found")
# 
# if quarters_data:
#     combined_quarters = pd.concat(quarters_data, ignore_index=True)
#     print(combined_quarters)

print("✓ Example patterns defined (uncomment to run)")

## 10. Troubleshooting and Diagnostics

Use these cells to diagnose issues with data extraction.

In [ ]:
# Diagnostic: View all available concepts in the income statement
def show_all_concepts(filing):
    """Display all XBRL concepts available in the income statement."""
    xbrl = filing.xbrl()
    income_stmt = xbrl.get_income_statement()
    
    if income_stmt is not None and not income_stmt.empty:
        concepts = income_stmt['concept'].unique() if 'concept' in income_stmt.columns else []
        print(f"Total unique concepts found: {len(concepts)}\n")
        
        for i, concept in enumerate(sorted(concepts), 1):
            print(f"{i:3d}. {concept}")
        
        return income_stmt
    else:
        print("No income statement data available")
        return None

# Uncomment to run diagnostics on the current filing:
# all_concepts_df = show_all_concepts(filing)
# all_concepts_df.head(20)

print("✓ Diagnostic functions ready (uncomment to run)")

In [ ]:
# Diagnostic: Search for specific concepts by keyword
def search_concepts(filing, keyword: str):
    """
    Search for XBRL concepts containing a specific keyword.
    
    Args:
        filing: Filing object
        keyword: Search term (case-insensitive)
    """
    xbrl = filing.xbrl()
    income_stmt = xbrl.get_income_statement()
    
    if income_stmt is not None and not income_stmt.empty and 'concept' in income_stmt.columns:
        matches = income_stmt[
            income_stmt['concept'].str.contains(keyword, case=False, na=False)
        ]
        
        if not matches.empty:
            print(f"Found {len(matches)} matches for '{keyword}':\n")
            return matches[['concept', 'value', 'label']].drop_duplicates(subset=['concept'])
        else:
            print(f"No matches found for '{keyword}'")
            return pd.DataFrame()
    else:
        print("No income statement data available")
        return pd.DataFrame()

# Example: Uncomment to search for specific concepts
# search_concepts(filing, "Revenue")
# search_concepts(filing, "EarningsPerShare")
# search_concepts(filing, "Interest")

print("✓ Search function ready (uncomment examples to run)")

## Summary

This notebook provides a complete solution for extracting income statements from SEC filings using edgartools.

### Key Features:
- ✓ Handles both 10-K (annual) and 10-Q (quarterly) filings
- ✓ Works for any fiscal year or quarter
- ✓ Extracts all required income statement line items
- ✓ Proper SEC identity setup (no 403 errors)
- ✓ Comprehensive error handling
- ✓ Validation and completeness checking
- ✓ Diagnostic tools for troubleshooting
- ✓ Export functionality

### How to Use:
1. Run cells 1-8 to set up functions (one time)
2. Modify the parameters in cell 10 (TICKER, FILING_TYPE, YEAR, QUARTER)
3. Run cells 11-15 to retrieve and display the income statement
4. Optional: Enable CSV export in cell 17

### Notes:
- Some line items may not be available for all companies (accounting standards vary)
- Use the diagnostic tools in cells 21-22 to explore what concepts are available
- XBRL concept names vary by company; the mapping handles common variations
- Values are typically in dollars (check the filing for currency/units)